### ISSUE TITLE
version: latest?

### ISSUE THREAD

**Issue by nmarun** [VaultSharp/VaultSharp#14]
Hi, is there a way I can request for the latest version of my secret? Say, if I don't pass the version parameter, can it get the latest version? This way I don't have to remember the version each of my secret.

Eg: ReadSecretAsync(path, mountPoint: "kv") // reads the latest version of the secret.

Thanks,
Arun

**Comment by nmarun** [comment]
@rajanadar, my bad. This works as expected.

**Comment by rajanadar** [comment]
Cool

**Comment by nmarun** [comment]
Good to know. Thanks.
